### ISSUE TITLE
Typo in Assignment 3

### ISSUE THREAD

**Issue by thebrianbug** [dcastl2/csc4103-fa2016#1]
I think there might be a typo in `assg/prog3/README.rst`.

Under 5. **Calculating the dot product.**

```
Assume that the sizes of u and v are even.
```

Did you mean: ?

```
Assume that the sizes of u and v are equal.
```

**Comment by thebrianbug** [comment]
Or possibly:

```
Assume that the sizes of u and v are both equal and even
```

Since the dot product is only defined if |u| = |v|

**Comment by dcastl2** [comment]
Implicitly, they must be equal. You can assume the problem in the
specification is solvable, then make any necessary assumptions or
interpretations of the spec that would be required in order to meet it.
If it is not solvable because of a requirement, let me know and I will
give you some points for catching such an error.

The reason it is specified that one may assume the sizes are even is to
simplify the work distribution, so that the work may be split cleanly in
half.  Although it is stated the array should be split in half, there is
nevertheless a common interpretation of the phrase "split in half"
applied to odd-sized arrays, which are split into pieces of size n/2 and
n/2+1.
